### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by nsrderooy** [Pepijn98/mdr-cli#5]
When trying to use a proxy server I get the following error message;

Either with `https_proxy=http://proxy01:3128 mdr domain list`
Or 
```
export https_proxy=http://proxy01:3128
mdr domain list
```

The error is as follows;
```
⠧ LoadingError: Request failed with status code 501
    at createError (/home/norbertr/.local/lib/node_modules/mdr-cli/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/norbertr/.local/lib/node_modules/mdr-cli/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/norbertr/.local/lib/node_modules/mdr-cli/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by nsrderooy** [comment]
I think this might be an issue on my end, testing now.

**Comment by nsrderooy** [comment]
Ok, it seems like either the code or node is doing something weird.

If I curl I get this message in my squid logs;
```
TCP_TUNNEL/200 5948 CONNECT manager.mijndomeinreseller.nl:443
```
If I use mdr-cli tool I see this;
```
TAG_NONE/501 4055 GET https://manager.mijndomeinreseller.nl/api/?
```
so either node or mdr-cli is doing something strange because for a https session CONNECT should be used so the MITM cannot see the `queryPath` and/or the `GET` it should only be able to see the domainname and the length.

**Comment by Pepijn98** [comment]
I've search for possible solutions but I don't know enough about proxies and how they work to understand what is happening here. You're welcome to open a PR if it's something related to the code. If you do open a PR please make a branch with the feature name etc.

**Comment by nsrderooy** [comment]
I'll check if I can come up with something.
